### ISSUE TITLE
Error when executing hadoop fs -mkdir /hdfs-dir

### ISSUE THREAD

**Issue by itsmedigio** [sunnyvale-academy/ITS-ICT_BigData#1]
When I execute that command, it just returns this error.

[hdfs@node1 ~]$ hadoop fs -mkdir /hdfs-dir
mkdir: Call From node1.example.com/192.168.199.2 to node1.example.com:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused

**Comment by denismaggior8** [comment]
Hi,
please verify that all the cluster services are up and running when logging into the Ambari web page.

<img width="1669" alt="cluster_services" src="https://user-images.githubusercontent.com/44289477/85116420-96155e80-b21d-11ea-9bdc-5ca2ea0a1e90.png">

If not, just select **Start All** when clicking on the three dots (...) near **Services**
